jobs:
  build:
    docker:
      - image: circleci/node:8.11.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      # Coverage
      - run: sudo npm install -g nyc --silent --quiet --no-save
      - run:
          name: coverage
          command: npm run coverage
      # Analysis
      - run: sudo npm install -g es6-plato --silent --quiet --no-save
      - run:
          name: analysis
          command: npm run analyze
  metrics:
    docker:
      - image: circleci/node:8.11.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install npm
          command: npm install
      - run:
         name: pregit
         command: npm install graphql graphql-request
      - run:
         name: git
         command: node metrics/git_metrics.js 


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - metrics:
          filters:
            branches:
              only: 
                - test
                - master
                - development