version: 2
jobs:
  build:
      - run:
          name: pregit
          command: npm install graphql graphql-request
          filters: 
              branches:
                  only:
                      - master
                      - test
                      - development
                      - stage
      - run:
          name: git
          command: node metrics/git_metrics.js
          filters: 
              branches:
                  only:
                      - master
                      - test
                      - development
                      - stage